# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import Previrt_pb2 as Previrt__pb2


class QueryOracleStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Query = channel.unary_unary(
        '/previrt.proto.QueryOracle/Query',
        request_serializer=Previrt__pb2.State.SerializeToString,
        response_deserializer=Previrt__pb2.Prediction.FromString,
        )


class QueryOracleServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Query(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_QueryOracleServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Query': grpc.unary_unary_rpc_method_handler(
          servicer.Query,
          request_deserializer=Previrt__pb2.State.FromString,
          response_serializer=Previrt__pb2.Prediction.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'previrt.proto.QueryOracle', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
